basicCRUD/config/routes.rb
Rails.application.routes.draw do
  resources :cobarails
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

basicCRUD/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

basicCRUD/app/models/cobarail.rb
class Cobarail < ApplicationRecord
end

basicCRUD/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

basicCRUD/app/controllers/cobarails_controller.rb
class CobarailsController < ApplicationController
  before_action :set_cobarail, only: %i[ show edit update destroy ]

  # GET /cobarails or /cobarails.json
  def index
    @cobarails = Cobarail.all
  end

  # GET /cobarails/1 or /cobarails/1.json
  def show
  end

  # GET /cobarails/new
  def new
    @cobarail = Cobarail.new
  end

  # GET /cobarails/1/edit
  def edit
  end

  # POST /cobarails or /cobarails.json
  def create
    @cobarail = Cobarail.new(cobarail_params)

    respond_to do |format|
      if @cobarail.save
        format.html { redirect_to @cobarail, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @cobarail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cobarail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cobarails/1 or /cobarails/1.json
  def update
    respond_to do |format|
      if @cobarail.update(cobarail_params)
        format.html { redirect_to @cobarail, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @cobarail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cobarail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cobarails/1 or /cobarails/1.json
  def destroy
    @cobarail.destroy
    respond_to do |format|
      format.html { redirect_to cobarails_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cobarail
      @cobarail = Cobarail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cobarail_params
      params.require(:cobarail).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

basicCRUD/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

basicCRUD/app/helpers/application_helper.rb
module ApplicationHelper
end

basicCRUD/app/helpers/cobarails_helper.rb
module CobarailsHelper
end

basicCRUD/app/helpers/home_helper.rb
module HomeHelper
end

basicCRUD/app/views/cobarails/_form.html.erb
<%= form_with(model: cobarail) do |form| %>
  <% if cobarail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cobarail.errors.count, "error") %> prohibited this Friend from being saved:</h2>

      <ul>
        <% cobarail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-text" %>
  </div>

  <div class="field mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-text" %>
  </div>

  <div class="field mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-text" %>
  </div>

  <div class="field mb-3">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-text" %>
  </div>

  <div class="field mb-3">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class: "form-text" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

basicCRUD/app/views/cobarails/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', cobarail: @cobarail %>

<br>
<%= link_to 'Show', @cobarail, class: "btn btn-primary" %>
<%= link_to 'Back', cobarails_path, class: "btn btn-primary" %>

basicCRUD/app/views/cobarails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friend List</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cobarails.each do |cobarail| %>
      <tr>
        <td><%= cobarail.first_name %></td>
        <td><%= cobarail.last_name %></td>
        <td><%= cobarail.email %></td>
        <td><%= cobarail.phone %></td>
        <td><%= cobarail.twitter %></td>
        <td><%= link_to 'Show', cobarail %></td>
        <td><%= link_to 'Edit', edit_cobarail_path(cobarail) %></td>
        <td><%= link_to 'Destroy', cobarail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friends', new_cobarail_path, class: "btn btn-primary" %>

basicCRUD/app/views/cobarails/new.html.erb
<h1>New Add Friend</h1>

<%= render 'form', cobarail: @cobarail %>
<br>
<%= link_to 'Back', cobarails_path, class: "btn btn-primary" %>

basicCRUD/app/views/cobarails/show.html.erb
<div class="card mb-3 text-white bg-dark" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="..." class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h3 class="card-title">
            <%= @cobarail.first_name %>
            <%= @cobarail.last_name %>
        </h3>
        <h5 class="card-subtitle mb-2 text-muted"> <%= @cobarail.twitter %> </h5>
        <h6 class="card-text">Email: <%= @cobarail.email %> </h6>
        <h6 class="card-text">Phone: <%= @cobarail.phone %> </h6>
        <%= link_to 'Edit', edit_cobarail_path(@cobarail), class: "btn btn-primary" %>
        <%= link_to 'Back', cobarails_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

basicCRUD/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'MyWebsite', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'About Me', home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Friends', cobarails_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Add Friend', new_cobarail_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

basicCRUD/app/views/home/about.html.erb
<h1>About Me</h1>

basicCRUD/app/views/home/index.html.erb
<h1>Hello World</h1>

basicCRUD/app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

basicCRUD/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cobarails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'home/header' %>
  <div class="container">
  <br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <br>
    <%= yield %>
  </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>